apiVersion: devopszurich.io/v1alpha1
kind: xDatabase
metadata:
  name: devops-zurich-database
  namespace: default
spec:
  sizeGb: 5
  instanceSize: small
  databaseName: devopsdb
  databaseUser: devopsuser
  # isHighlyAvailable: false
  # backupRetentionDays: 7
  # enableSSL: true
  # deletionProtection: false
